* Importar Numpy :

In [3]:
import numpy as np

* NP.ARRAY : Es el constructor de un array , en este caso hacemos uno de dimensión cero.

In [17]:
mi_array = np.array(50)
print(mi_array)
print (f'Este array es de dimensión : {mi_array.ndim}') # ndim indica la dimensión del array

50
Este array es de dimensión : 0


* Construccion de arrays de dimensión 1:

In [18]:
mi_array = np.array([2,3,5])
print(mi_array)
print (f'Este array es de dimensión : {mi_array.ndim}')

[2 3 5]
Este array es de dimensión : 1


* Constuccion de arrays de dimensión 2:

In [19]:
mi_array = np.array([[1,2,3],[4,5,6]]) # las dimensiones se pueden identificar por los []
print(mi_array)
print (f'Este array es de dimensión : {mi_array.ndim}')

[[1 2 3]
 [4 5 6]]
Este array es de dimensión : 2


* Construccion de arrays de dimensión 3:

In [20]:
mi_array = np.array([[[1,2,3],[4,5,6]],[[5,8,9],[8,3,9]]])
print(mi_array)
print (f'Este array es de dimensión : {mi_array.ndim}')

[[[1 2 3]
  [4 5 6]]

 [[5 8 9]
  [8 3 9]]]
Este array es de dimensión : 3


# Llamar un elemento del array
* Para llamar un elemento los indices y slices son iguales que en las listas:

In [35]:
mi_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(mi_array[0])
print(mi_array[4:7])

1
[5 6 7]


* Si tenemos un array de 2 dimensiones:

In [40]:
mi_array = np.array([[1,2,3],[4,5,6]])
print (f'Este array es de dimensión : {mi_array.ndim}')
print(mi_array)
print(mi_array[1,2]) # Se le indica la fila y la columna

Este array es de dimensión : 2
[[1 2 3]
 [4 5 6]]
6


* Si tenemos un array de 3 dimensiones:

In [41]:
mi_array = np.array([[[1,2,3],[4,5,6]],[[8,9,0],[12,13,15]]])
print (f'Este array es de dimensión : {mi_array.ndim}')
print(mi_array)
print(mi_array[1,0,1]) # profundidad,filas y columnas.

Este array es de dimensión : 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9  0]
  [12 13 15]]]
9


# Forma del array
* SHAPE: Nos dice la forma que tiene el array es decir cuantas filas X cuantas columnas.

In [5]:
mi_array = np.array([1,2,3])
print (f'Este array es de dimensión : {mi_array.ndim}')
print(np.shape(mi_array)) # La forma dice que tiene 1 dimensión con 3 elementos

Este array es de dimensión : 1
(3,)


In [47]:
mi_array = np.array([[1,2,3],[4,5,6]])
print (f'Este array es de dimensión : {mi_array.ndim}')
print(np.shape(mi_array)) # La forma dice que tiene 2 dimensiones con 3 elementos

Este array es de dimensión : 2
(2, 3)


* RESHAPE: nos sirve para cambiar la forma de un array, debe coincidir en el len final .

In [6]:
mi_array = np.array([[1,2,3,4],[5,6,7,8]])
print('Array original:')
print(mi_array) # Originalmente era de 2,4
mi_array = mi_array.reshape(4,2) # Lo cambio a 4,2
print('Array cambiado:')
print(mi_array)

Array original:
[[1 2 3 4]
 [5 6 7 8]]
Array cambiado:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Iterar el array
* Se hace con for al igual que una iteración normal en pytho

In [55]:
mi_array = np.array([[1,2,3,4],[5,6,7,8]])
print (f'Este array es de dimensión : {mi_array.ndim}')
for fila in mi_array:
    print(fila)

Este array es de dimensión : 2
[1 2 3 4]
[5 6 7 8]


In [57]:
mi_array = np.array([[[1,2,3],[4,5,6]],[[8,9,0],[12,13,15]]])
print (f'Este array es de dimensión : {mi_array.ndim}')
for matriz in mi_array: # primero itera las matrices del array
    for fila in matriz: # luego itera las filas de las matrices
        print(fila)

Este array es de dimensión : 3
[1 2 3]
[4 5 6]
[8 9 0]
[12 13 15]


# Concatenar:

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2)) # junta los arrays en una sola dimensión
print (f'Este array es de dimensión : {arr.ndim}')

print(arr)

Este array es de dimensión : 1
[1 2 3 4 5 6]


* Al concatenar los arrays no se altera la dimensión

In [11]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2))    
print (f'Este array es de dimensión : {arr.ndim}')

print(arr)

Este array es de dimensión : 2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2),axis=1)    # axis=1 columnas 
print (f'Este array es de dimensión : {arr.ndim}')

print(arr)

Este array es de dimensión : 2
[[1 2 5 6]
 [3 4 7 8]]


# Split
* Sirve para separar un array:

In [13]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3) # _split es lo que divide y arr,3 indica las partes en las que se va a dividir
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Where
* Buscar dentro de un array:

In [11]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 5)  # Te devuelve el indice donde está el elemento que hemos indicado
print(x)

(array([4], dtype=int64),)


# Sort
* Ordena un array de menor a mayor si son números y alfabéticamente si son palabras .

In [17]:
arr = np.array([3,2,0,1])
print(np.sort(arr)) # sort ordena el array 

[0 1 2 3]


# RANDOM
* Importar el módulo:

In [13]:
from numpy import random 

* Randint()

In [14]:
numero = random.randint(10) # Cada que se ejecute generará números enteros del 1 al 9 aleatoriamente 
print(numero)

2


In [60]:
numero = random.rand() # Cada que se ejecute generará números float aleatoriamente 
print(round(numero, 2) + 5) # round,2 indica que queremos que muestre 2 decimales y el +5 que empiece desde 5.00 hasta 5.99

5.61


In [66]:
numeros = random.randint(10, size = (3,5)) # 3,5 es el tamaño de la matriz
print(numeros)

[[7 2 6 4 1]
 [9 1 6 6 8]
 [0 7 9 5 6]]


In [68]:
numeros = random.rand(3,5) # 3,5 es el tamaño de la matriz
print(numeros)

[[0.09513159 0.41806623 0.68758347 0.66379977 0.64271833]
 [0.57074409 0.18058716 0.53610316 0.48885257 0.09333217]
 [0.80381825 0.93794875 0.35006335 0.7947091  0.01437666]]


# Choice
* Escoje un elemento al azar

In [78]:
lista_nombres = ['Javi', 'Nat', 'Germán', 'Mica','Haile']
ganador = random.choice(lista_nombres)  # Choice escoje un elemento aleatoriamente de la lista
print(f'El ganador del sorteo es: {ganador}')

El ganador del sorteo es: Javi


In [82]:
lista_nombres = ['Javi', 'Nat', 'Germán', 'Mica','Haile']
ganador = random.choice(lista_nombres, size = (2))  # size = (2) elegirá 2 elementos y si indico (2,5) genera una matriz
print(f'El ganador del sorteo es: {ganador}')

El ganador del sorteo es: ['Mica' 'Nat']
